# This is a basic workflow to help you get started with GitHub Actions

name: Run generate shell script

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron:  '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 
        
      - name: Run a script to build a json file with details about various builds for various platforms
        run: sh ./generate3.sh

      - name: Run a script just to check period update of file
        run: sh ./periodic_test.sh

      - name: Run a set of commands
        run: |
          echo Nothing to see in the multi-line script
          echo Here is what is in the folder
          ls -a
